INTEGER FUNCTION FACTORIAL(N)
  INTEGER, INTENT(IN) :: N
  IF (N <= 1) THEN
    FACTORIAL = 1
  ELSE
    FACTORIAL = N * FACTORIAL(N - 1)
  END IF
END FUNCTION FACTORIAL

PROGRAM FACT_DEMO
  INTEGER :: I, RESULT
  DO I = 1, 10
    RESULT = FACTORIAL(I)
    PRINT *, I, "! =", RESULT
  END DO
END PROGRAM FACT_DEMO
